default_language_version:
    python: python3.8
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-builtin-literals
    -   id: check-ast
    -   id: check-json
    -   id: detect-private-key
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black

-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
